//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagement.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HotelManagementEntities : DbContext
    {
        public HotelManagementEntities()
            : base("name=HotelManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bill> Bills { get; set; }
        public virtual DbSet<Furniture> Furnitures { get; set; }
        public virtual DbSet<FurnitureReceipt> FurnitureReceipts { get; set; }
        public virtual DbSet<FurnitureReceiptDetail> FurnitureReceiptDetails { get; set; }
        public virtual DbSet<Parameter> Parameters { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductReceipt> ProductReceipts { get; set; }
        public virtual DbSet<ProductReceiptDetail> ProductReceiptDetails { get; set; }
        public virtual DbSet<ProductUsing> ProductUsings { get; set; }
        public virtual DbSet<RentalContract> RentalContracts { get; set; }
        public virtual DbSet<RentalContractDetail> RentalContractDetails { get; set; }
        public virtual DbSet<Revenue> Revenues { get; set; }
        public virtual DbSet<RevenueProduct> RevenueProducts { get; set; }
        public virtual DbSet<RevenueRoomType> RevenueRoomTypes { get; set; }
        public virtual DbSet<Room> Rooms { get; set; }
        public virtual DbSet<RoomType> RoomTypes { get; set; }
        public virtual DbSet<RoomTypeFurniture> RoomTypeFurnitures { get; set; }
        public virtual DbSet<Staff> Staffs { get; set; }
        public virtual DbSet<SurchargeRate> SurchargeRates { get; set; }
        public virtual DbSet<Trouble> Troubles { get; set; }
    }
}
