//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductReceiptDetail
    {
        public string ProductReceiptDetailId { get; set; }
        public string ProductReceiptId { get; set; }
        public string ProductId { get; set; }
        public Nullable<double> ImportPrice { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual ProductReceipt ProductReceipt { get; set; }
    }
}
